export const ADD_PRODUCT_TO_LIST = "ADD_PRODUCT_TO_LIST";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const INCREASE_PRODUCT_AMOUNT = "INCREASE_PRODUCT_AMOUNT";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";